"""empty message

Revision ID: 41281de9e92c
Revises: 8ccd24d624dc
Create Date: 2022-01-07 11:30:47.315582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41281de9e92c'
down_revision = '8ccd24d624dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('coach', sa.Integer(), nullable=True))
    op.drop_constraint('team_player_6_id_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'player', ['coach'], ['id'])
    op.drop_column('team', 'player_6_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('player_6_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_player_6_id_fkey', 'team', 'player', ['player_6_id'], ['id'])
    op.drop_column('team', 'coach')
    # ### end Alembic commands ###
