"""empty message

Revision ID: a7c0085e80f9
Revises: 4301bad0b5d7
Create Date: 2022-01-01 19:26:34.803430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c0085e80f9'
down_revision = '4301bad0b5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('nickname', sa.String(length=128), nullable=False))
    op.add_column('player', sa.Column('hltv_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'player', ['hltv_id'])
    op.drop_column('player', 'nick_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('nick_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'hltv_id')
    op.drop_column('player', 'nickname')
    # ### end Alembic commands ###
