"""empty message

Revision ID: 2449eef34aed
Revises: ba2ba215dc17
Create Date: 2022-01-07 13:08:04.580310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2449eef34aed'
down_revision = 'ba2ba215dc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('match', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization', sa.Column('alias_1', sa.String(length=64), nullable=True))
    op.add_column('organization', sa.Column('alias_2', sa.String(length=64), nullable=True))
    op.add_column('organization', sa.Column('current_team_id', sa.Integer(), nullable=False))
    op.add_column('organization', sa.Column('hltv_id', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'organization', ['hltv_id'])
    op.create_unique_constraint(None, 'organization', ['alias_1'])
    op.create_unique_constraint(None, 'organization', ['alias_2'])
    op.create_foreign_key(None, 'organization', 'team', ['current_team_id'], ['id'])
    op.add_column('team', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('team', sa.Column('organization_name', sa.String(length=64), nullable=False))
    op.add_column('team', sa.Column('team_nicknames', sa.String(length=128), nullable=False))
    op.add_column('team', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('team', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'team', ['team_nicknames'])
    op.drop_constraint('team_organization_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'organization', ['organization_name'], ['name'])
    op.create_foreign_key(None, 'team', 'organization', ['organization_id'], ['id'])
    op.drop_column('team', 'organization')
    op.drop_column('team', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('organization', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_organization_fkey', 'team', 'organization', ['organization'], ['id'])
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'updated_at')
    op.drop_column('team', 'created_at')
    op.drop_column('team', 'team_nicknames')
    op.drop_column('team', 'organization_name')
    op.drop_column('team', 'organization_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_column('organization', 'updated_at')
    op.drop_column('organization', 'created_at')
    op.drop_column('organization', 'hltv_id')
    op.drop_column('organization', 'current_team_id')
    op.drop_column('organization', 'alias_2')
    op.drop_column('organization', 'alias_1')
    op.drop_column('match', 'updated_at')
    op.drop_column('match', 'created_at')
    # ### end Alembic commands ###
