"""Add players, org and team

Revision ID: 4301bad0b5d7
Revises: 56d27ca0857e
Create Date: 2022-01-01 16:38:10.675206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301bad0b5d7'
down_revision = '56d27ca0857e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=False),
    sa.Column('player_1_id', sa.Integer(), nullable=False),
    sa.Column('player_2_id', sa.Integer(), nullable=False),
    sa.Column('player_3_id', sa.Integer(), nullable=False),
    sa.Column('player_4_id', sa.Integer(), nullable=False),
    sa.Column('player_5_id', sa.Integer(), nullable=False),
    sa.Column('player_6_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['player_1_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_3_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_4_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_5_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_6_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('organization')
    # ### end Alembic commands ###
