version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "cbdb-api"
          ContainerPort: 80
          NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["cbdb-vpc-subnet-public2-eu-central-1b", "cbdb-vpc-subnet-public1-eu-central-1a"]
              SecurityGroups: ["default"]
              AssignPublicIp: "ENABLED"